services:
  admin_service:
    build:
      context: ./admin_service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    networks:
      - petfinder_network

  pet_search_service:
    build:
      context: ./pet_search_service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    networks:
      - petfinder_network
    environment:
      - ADMIN_SERVICE_URL=http://admin_service:5003/events
      - PETFINDER_API_KEY=jHY0pnScj9SogAzR1rKKSFLqHCrSqOywuib7HaewzdTj8ZsLI4
      - PETFINDER_API_SECRET=A82kmUWeqG8EC3s9Z8xV0yY4gqS4qis24XeKMa5A

  user_management_service:
    build:
      context: ./user_management_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - petfinder_network
    environment:
      - ADMIN_SERVICE_URL=http://admin_service:5003/events

networks:
  petfinder_network:
    driver: bridge
