version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  pet_search_service:
    build:
      context: ./pet_search_service
    depends_on:
      - kafka
    ports:
      - "5002:5002"
    environment:
      - KAFKA_BROKER=kafka:9092

  user_management_service:
    build:
      context: ./user_management_service
    depends_on:
      - kafka
    ports:
      - "5001:5001"
    environment:
      - KAFKA_BROKER=kafka:9092

  admin_service:
    build:
      context: ./admin_service
    depends_on:
      - kafka
    ports:
      - "5003:5003"
    environment:
      - KAFKA_BROKER=kafka:9092
